add package manager command heads-up to checklist script

diff --git a/stowage/universal-scripts/.local/bin/package-update-check b/stowage/universal-scripts/.local/bin/package-update-check
--- a/stowage/universal-scripts/.local/bin/package-update-check
+++ b/stowage/universal-scripts/.local/bin/package-update-check
@@ -24,7 +24,7 @@ main() {
 	fi
 
 	if (( ${#require_sudo[@]} > 0 )); then
-		>&2 printf "Root privileges required for: %s\n" "${require_sudo[*]}"
+		IFS=$' '; >&2 printf "Root privileges required for: %s\n" "${require_sudo[*]}"; IFS=$'\n\t'
 		>&2 echo "The script will now prompt you to authenticate using sudo"
 		>&2 sudo echo "Successfully elevated with sudo" || exit 1
 	fi
