update the package update check to work in parallel and do other things good too

diff --git a/stowage/universal-scripts/.local/bin/package-update-check b/stowage/universal-scripts/.local/bin/package-update-check
--- a/stowage/universal-scripts/.local/bin/package-update-check
+++ b/stowage/universal-scripts/.local/bin/package-update-check
@@ -1,90 +1,141 @@
 #!/usr/bin/env bash
-set -euo pipefail
+set -u
 IFS=$'\n\t'
 
-FILE_PATH="$HOME/upgradable-packages.txt"
+# Figures out what package managers live on the system, then executes their "get upgradable
+# packages" flow in parallel.
 
-if [ -f "$FILE_PATH" ]; then
-	rm "$FILE_PATH"
-fi
+# TODO: consider allowing an environment variable to direct the output of this script
+#       (e.g. to a known file location instead of stdout)
 
-# check for apt-get because just "apt" can also be a java executable
-if command -v apt-get &> /dev/null; then
-	echo -e "Fetching apt packages..."
-	sudo apt-get update &> /dev/null
-	{
-		echo -e "### Upgradable packages from apt: ###\n";
-		apt list --upgradable;
-		echo -e "\n\n";
-	} >> "$FILE_PATH"
-fi
+# file path to export output to instead of printing to stdout
+UPDATE_LIST_OUTPUT_FILE=${UPDATE_LIST_OUTPUT_FILE:-}
 
-if command -v dnf &> /dev/null; then
-	echo -e "Fetching dnf packages..."
-	# we could do this in one line, but this way we don't get the progress updates in the output
-	dnf check-update --refresh &> /dev/null
-	{
-		echo -e "### Upgradable packages from dnf: ###\n";
-		dnf list --updates;
-		echo -e "\n\n";
-	} >> "$FILE_PATH"
-fi
+main() {
+	local -a require_sudo
+	local -a check_commands
+	get_check_command_list check_commands require_sudo
 
-HOMEBREW_REMINDER=$(
-cat <<-'EOF'
-	To update homebrew itself, run "homebrew update"
-	To update homebrew-managed packages, run "homebrew upgrade"
-	EOF
-)
+	# All of homebrew basically assumes that you will only ever use it as a single user on the
+	# system, which is hard to square with some system package managers which require running as
+	# root to update package metadata caches. The solution we use here is to require the overall
+	# script to be run as non-root, and then "cache" a sudo invocation so that subsequent sudo
+	# invocations will succeed non-interactively.
+	if (( EUID == 0)); then
+		>&2 echo "This script cannot be run overall as root, try again as a non-root user"
+		exit 1
+	fi
 
-if command -v brew &> /dev/null; then
-	echo -e "Fetching homebrew packages..."
+	if (( ${#require_sudo[@]} > 0 )); then
+		>&2 printf "Root privileges required for: %s\n" "${require_sudo[*]}"
+		>&2 echo "The script will now prompt you to authenticate using sudo"
+		>&2 sudo echo "Successfully elevated with sudo" || exit 1
+	fi
 
-	# brew prints status information to stderr, which is noisy and annoying
-	BASE_RESULTS=$(brew upgrade --dry-run 2> /dev/null)
-	PACKAGE_LIST=$(echo "$BASE_RESULTS" | rg "\->" -M 0 --no-context-separator || true)
-	{
-		echo -e "### Upgradable packages from homebrew: ###\n";
-		if [[ -n $PACKAGE_LIST ]]; then
-			echo -e "$PACKAGE_LIST\n";
-		fi
-		echo -e "$HOMEBREW_REMINDER\n";
-	} >> "$FILE_PATH"
-fi
+	output=$(parallel ::: "${check_commands[@]}")
+	output+=$'\n\n\n'
+	output+="This information generated at: $(date)"
 
-if command -v flatpak &> /dev/null; then
-	echo -e "Fetching flatpak packages..."
-	{
-		echo -e "### Upgradable packages from flatpak: ###\n";
-		FLATPAK_OUTPUT=$(flatpak remote-ls --updates);
-		if [[ -n $FLATPAK_OUTPUT ]]; then
-			echo -e "$FLATPAK_OUTPUT\n\n";
-		fi
-	} >> "$FILE_PATH"
-fi
-
-# parameter 1: output file path
-# parameter 2: output of zypper dist-upgrade dry run
-function print_zypper_summary()
-{
-	local OUTPUT_FILE=$1
-	local ZYPPER_OUTPUT=$2
-	local IMPORTANT_PACKAGES
-	IMPORTANT_PACKAGES=$( \
-		echo "$ZYPPER_OUTPUT" | \
-		rg "^openSUSE-release\s|^kernel\s|^nvidia-video-[[:alnum:]]+\s|^neovim\s" -A1 \
-		--no-context-separator \
-		|| true \
-	);
-	local PACKAGE_SUMMARY
-	PACKAGE_SUMMARY=$( \
-		echo "$ZYPPER_OUTPUT" | \
-		rg "packages to upgrade" --no-context-separator || true \
-	);
-
-	{
-		echo -e "### Packages upgraded in most recent dist-upgrade snapshot: ###\n"
-		echo -e "$PACKAGE_SUMMARY\n"
-		echo -e "$IMPORTANT_PACKAGES\n"
-	} >> "$OUTPUT_FILE"
+	if [[ -n "$UPDATE_LIST_OUTPUT_FILE" ]]; then
+		echo "$output" > "$UPDATE_LIST_OUTPUT_FILE"
+		>&2 echo "Updatable packages output exported to: $UPDATE_LIST_OUTPUT_FILE"
+	else
+		echo "$output"
+	fi
 }
+
+# arg 1: array name to populate with check commands
+# arg 2: array name to populate with commands which require root access
+get_check_command_list() {
+	declare -n output_commands=$1
+	declare -n output_require_sudo=$2
+
+	if type -t apt-get > /dev/null ; then
+		output_require_sudo+=("apt-get")
+		output_commands+=('get_apt_updates')
+	fi
+	if type -t dnf > /dev/null ; then
+		output_commands+=('get_dnf_updates')
+	fi
+	if type -t brew > /dev/null ; then
+		output_commands+=('get_brew_updates')
+	fi
+	if type -t flatpak > /dev/null ; then
+		output_commands+=('get_flatpak_updates')
+	fi
+	if type -t zypper > /dev/null ; then
+		output_require_sudo+=("zypper")
+		output_commands+=('get_zypper_updates')
+		# output_commands+=('get_zypper_updates_test')
+	fi
+}
+
+# NOTE: any functions which will be invoked within a parallel process must be exported with -f
+
+get_apt_updates() {
+	sudo apt-get update > /dev/null
+	section_header "APT PACKAGES"
+	apt list --upgradable
+	echo ""
+}
+export -f get_apt_updates
+
+get_dnf_updates() {
+	dnf check-update --refresh > /dev/null
+	section_header "APT PACKAGES"
+	dnf list --updates
+	echo ""
+}
+export -f get_dnf_updates
+
+get_brew_updates() {
+	# brew is VERY spammy to stderr
+	section_header "HOMEBREW PACKAGES"
+	brew outdated --verbose
+
+	echo ""
+	echo "Homebrew reminder:"
+	echo "  To update homebrew itself, run \"homebrew update\""
+	echo "  To update homebrew-managed packages, run \"homebrew upgrade\""
+	echo ""
+}
+export -f get_brew_updates
+
+get_flatpak_updates() {
+	section_header "FLATPAK PACKAGES"
+	flatpak remote-ls --updates --columns=name,version,download-size \
+		| column --table --separator $'\t' --output-width 100
+	echo ""
+}
+export -f get_flatpak_updates
+
+get_zypper_updates() {
+	section_header "ZYPPER PACKAGES"
+	sudo zypper refresh > /dev/null
+	# TODO: consider filtering & re-formatting the output of zypper list-updates:
+	#   - remove header lines and progress updates
+	#   - do not print arch
+	#   - scrunch versions to make them take up less space
+	#   - reorder everything to make it more scannable
+	#   - pull out some notable packages of interest (like kernel, tumbleweed release, nvidia
+	#     drivers, etc) to display separately
+	zypper list-updates
+	echo ""
+}
+export -f get_zypper_updates
+
+get_zypper_updates_test() {
+	section_header "ZYPPER PACKAGES (MOCKED)"
+	sudo echo "This is mocked output from zypper. Pretend it's really long."
+	echo ""
+}
+export -f get_zypper_updates_test
+
+# arg 1: name of section to be displayed
+section_header() {
+	local section_header=$1
+	echo -e "\n§ $section_header\n"
+}
+export -f section_header
+
+main
